app:
  port: 3002
database:
  url: study_documentation_api
  dbuser: henriquechaves
  dbpassword: henrique@123
  connection_uri: 'mongodb://henriquechaves:henriquechaves@ds231740.mlab.com:31740/study_documentation_api'
token:
  key: StudyDocumentationApi
